### ISSUE TITLE
handle twilio 404 errors 

### ISSUE THREAD

**Issue by nidhhoggr** [nidhhoggr/phoneSpamFilter#2]
Right now were just blindly caching 404 errors.
```
2019-05-09T14:08:33.884Z phoneSpamFilter:modules:twilio Fetching https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@lookups.twilio.com/v1/PhoneNumbers/+1n= 1407982/?AddOns=nomorobo_spamscore
2019-05-09T14:08:34.224Z phoneSpamFilter:modules:twilio {
  code: 20404,
  message: 'The requested resource /PhoneNumbers/+1n= 1407982 was not found',
  more_info: 'https://www.twilio.com/docs/errors/20404',
  status: 404
}
2019-05-09T14:08:34.224Z phoneSpamFilter:modules:cache Attempting to set phoneSpamFilter:spamScoreByPhoneNumber:nomorobo_spamscore:1n= 1407982 to {"code":20404,"message":"The requested resource /PhoneNumbers/+1n= 1407982 was not found","more_info":"https://www.twilio.com/docs/errors/20404","status":404}
2019-05-09T14:08:34.227Z phoneSpamFilter:routes:spamScoreByPhoneNumber TypeError: Cannot read property 'results' of undefined
    at Object.deepValue (/var/www/vhosts/phoneSpamFilter/src/shared/deepValue.js:3:14)
    at Object.isSpamFromLookupResponse (/var/www/vhosts/phoneSpamFilter/src/shared/twilio.js:17:42)
    at /var/www/vhosts/phoneSpamFilter/src/routes/get/spamScoreByPhoneNumber.js:51:49
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by nidhhoggr** [comment]
It turns out that in this case it's actually preferred to cache the 404 error, especially given the nature of the request which contained an erroneous phone number. Instead we get rid of the type error and fix our assertion to handle undefined value properly.
